### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tegarajipangestu** [collaboratrio/datacollaboratr#1]
- [x] Baca paper Collaborative oriented middleware
- [ ] Bikin list fungsi di wrangler
- [x] Belajar OOP Javascript
- [ ] Baca paper tentang ekstraksi data
- [ ] Tambahin gap analysis antara berbagai software yang ada
